from iso14001_rules_check_tools.models import Clause


CLAUSE_CATALOG: tuple[Clause, ...] = (
    Clause(
        clause_id="4.1",
        clause_title="Understanding the organization and its context",
        clause_title_zh="Understanding the organization and its context",
        keywords=("organization", "context", "internal issues", "external issues", "environmental context"),
        description="Look for text about the organization, its context, and relevant internal or external issues.",
    ),
    Clause(
        clause_id="4.2",
        clause_title="Understanding the needs and expectations of interested parties",
        clause_title_zh="Understanding the needs and expectations of interested parties",
        keywords=("interested parties", "stakeholder", "requirements", "needs and expectations"),
        description="Look for identified interested parties and their relevant requirements.",
    ),
    Clause(
        clause_id="4.3",
        clause_title="Determining the scope of the environmental management system",
        clause_title_zh="Determining the scope of the environmental management system",
        keywords=("scope", "environmental management system", "ems scope"),
        description="Look for the documented scope of the EMS and any applicable boundaries.",
    ),
    Clause(
        clause_id="4.4",
        clause_title="Environmental management system",
        clause_title_zh="Environmental management system",
        keywords=("environmental management system", "EMS", "processes", "process interaction"),
        description="Look for the organization's environmental management system and how its processes interact.",
    ),
    Clause(
        clause_id="5.1",
        clause_title="Leadership and commitment",
        clause_title_zh="Leadership and commitment",
        keywords=("leadership", "commitment", "top management"),
        description="Look for top management leadership and commitment to the EMS.",
    ),
    Clause(
        clause_id="5.2",
        clause_title="Environmental policy",
        clause_title_zh="Environmental policy",
        keywords=("environmental policy", "policy", "pollution prevention", "protection of the environment"),
        description="Look for an environmental policy that is established, communicated, and available as a statement of intent.",
    ),
    Clause(
        clause_id="5.3",
        clause_title="Organizational roles, responsibilities and authorities",
        clause_title_zh="Organizational roles, responsibilities and authorities",
        keywords=("responsibility", "authority", "roles", "responsibilities"),
        description="Look for assigned responsibilities and authorities within the organization.",
    ),
    Clause(
        clause_id="6.1",
        clause_title="Actions to address risks and opportunities",
        clause_title_zh="Actions to address risks and opportunities",
        keywords=("risk", "opportunity", "actions to address", "risks and opportunities"),
        description="Look for risks, opportunities, and actions to address them.",
    ),
    Clause(
        clause_id="6.1.1",
        clause_title="General",
        clause_title_zh="General",
        keywords=("risks and opportunities", "general"),
        description="Look for the general requirements for planning actions.",
    ),
    Clause(
        clause_id="6.1.2",
        clause_title="Environmental aspects",
        clause_title_zh="Environmental aspects",
        keywords=("environmental aspect", "environmental aspects", "significant environmental aspect", "impact", "life cycle"),
        description="Look for environmental aspects, significant aspects, and life cycle perspective.",
    ),
    Clause(
        clause_id="6.1.3",
        clause_title="Compliance obligations",
        clause_title_zh="Compliance obligations",
        keywords=(
            "compliance obligation",
            "applicable requirements",
            "determine applicable requirements",
            "applicable requirements for",
            "applicable requirements for its environmental aspects",
            "legal requirement",
            "other requirement",
        ),
        description="Look for legal and other requirements that the organization must comply with.",
    ),
    Clause(
        clause_id="6.1.4",
        clause_title="Planning action",
        clause_title_zh="Planning action",
        keywords=("planning action", "plan action", "action plan", "planning"),
        description="Look for planned actions to address environmental aspects, obligations, risks, and opportunities.",
    ),
    Clause(
        clause_id="6.2",
        clause_title="Environmental objectives and planning to achieve them",
        clause_title_zh="Environmental objectives and planning to achieve them",
        keywords=("environmental objective", "environmental objectives", "objective", "target", "planning"),
        description="Look for environmental objectives and plans to achieve them.",
    ),
    Clause(
        clause_id="6.2.1",
        clause_title="Environmental objectives",
        clause_title_zh="Environmental objectives",
        keywords=("environmental objectives", "objective", "targets"),
        description="Look for environmental objectives that are established at relevant functions and levels.",
    ),
    Clause(
        clause_id="6.2.2",
        clause_title="Planning actions to achieve environmental objectives",
        clause_title_zh="Planning actions to achieve environmental objectives",
        keywords=("planning actions", "action plan", "environmental objective", "responsibility", "time frame"),
        description="Look for actions, responsibilities, and time frames to achieve environmental objectives.",
    ),
    Clause(
        clause_id="7.1",
        clause_title="Resources",
        clause_title_zh="Resources",
        keywords=("resources", "provide", "infrastructure", "environment"),
        description="Look for resources required for the EMS.",
    ),
    Clause(
        clause_id="7.2",
        clause_title="Competence",
        clause_title_zh="Competence",
        keywords=("competence", "competent", "training"),
        description="Look for competence, training, and actions to achieve competence.",
    ),
    Clause(
        clause_id="7.3",
        clause_title="Awareness",
        clause_title_zh="Awareness",
        keywords=("awareness", "aware", "policy awareness"),
        description="Look for awareness of the environmental policy, objectives, and contribution to EMS effectiveness.",
    ),
    Clause(
        clause_id="7.4",
        clause_title="Communication",
        clause_title_zh="Communication",
        keywords=("communication", "communicate"),
        description="Look for internal and external communication requirements.",
    ),
    Clause(
        clause_id="7.4.1",
        clause_title="General",
        clause_title_zh="General",
        keywords=("communication", "general"),
        description="Look for general communication requirements.",
    ),
    Clause(
        clause_id="7.4.2",
        clause_title="Internal communication",
        clause_title_zh="Internal communication",
        keywords=("internal communication", "communicate internally"),
        description="Look for how the organization communicates internally about the EMS.",
    ),
    Clause(
        clause_id="7.4.3",
        clause_title="External communication",
        clause_title_zh="External communication",
        keywords=("external communication", "communicate externally"),
        description="Look for how the organization communicates externally about the EMS.",
    ),
    Clause(
        clause_id="7.5",
        clause_title="Documented information",
        clause_title_zh="Documented information",
        keywords=("documented information", "document", "records"),
        description="Look for controlled documents, records, and other documented information.",
    ),
    Clause(
        clause_id="8.1",
        clause_title="Operational planning and control",
        clause_title_zh="Operational planning and control",
        keywords=(
            "operational planning",
            "operational control",
            "operational controls",
            "criteria for processes",
            "outsourced processes",
            "planned changes",
        ),
        description="Look for operational planning and control for EMS processes.",
    ),
    Clause(
        clause_id="8.2",
        clause_title="Emergency preparedness and response",
        clause_title_zh="Emergency preparedness and response",
        keywords=("emergency", "preparedness", "response", "spill", "incident", "drill"),
        description="Look for emergency preparedness and response arrangements.",
    ),
    Clause(
        clause_id="9.1",
        clause_title="Monitoring, measurement, analysis and evaluation",
        clause_title_zh="Monitoring, measurement, analysis and evaluation",
        keywords=("monitoring", "measurement", "analysis", "evaluation", "environmental performance"),
        description="Look for monitoring, measurement, analysis, and evaluation activities.",
    ),
    Clause(
        clause_id="9.1.1",
        clause_title="General",
        clause_title_zh="General",
        keywords=("monitoring", "measurement", "analysis"),
        description="Look for the general requirements for monitoring and evaluation.",
    ),
    Clause(
        clause_id="9.1.2",
        clause_title="Evaluation of compliance",
        clause_title_zh="Evaluation of compliance",
        keywords=("evaluation of compliance", "compliance evaluation", "legal compliance", "assess compliance"),
        description="Look for the process used to evaluate compliance with legal and other requirements.",
    ),
    Clause(
        clause_id="9.2",
        clause_title="Internal audit",
        clause_title_zh="Internal audit",
        keywords=("internal audit", "audit", "auditor"),
        description="Look for internal audit planning, execution, and reporting.",
    ),
    Clause(
        clause_id="9.3",
        clause_title="Management review",
        clause_title_zh="Management review",
        keywords=("management review", "review meeting"),
        description="Look for management review inputs, outputs, and decisions.",
    ),
    Clause(
        clause_id="10.1",
        clause_title="General",
        clause_title_zh="General",
        keywords=("improvement", "general improvement"),
        description="Look for general improvement requirements.",
    ),
    Clause(
        clause_id="10.2",
        clause_title="Nonconformity and corrective action",
        clause_title_zh="Nonconformity and corrective action",
        keywords=("corrective action", "nonconformity", "root cause", "corrective"),
        description="Look for corrective action to address nonconformities and their causes.",
    ),
    Clause(
        clause_id="10.3",
        clause_title="Continual improvement",
        clause_title_zh="Continual improvement",
        keywords=("continual improvement", "improvement", "enhance"),
        description="Look for continual improvement of the EMS.",
    ),
)


def default_clause_catalog() -> tuple[Clause, ...]:
    return CLAUSE_CATALOG
